import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14
offset = { x = 0, y = 2 }

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
